# Generated by Django 3.0.6 on 2020-05-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='产品代码')),
                ('category', models.IntegerField(choices=[[0, '精品'], [1, '轮胎'], [2, '耗材']], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 't_product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='客户手机')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售单价')),
                ('volumes', models.IntegerField(verbose_name='销售数量')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='合计金额')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='product.Product')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 't_order',
            },
        ),
    ]
