# Generated by Django 3.0.6 on 2020-05-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
